In [54]:
#Dependencies
import pandas as pd 
from matplotlib import pyplot as plt
import numpy as np 
import seaborn as sns 
import requests as req
import random 

#Read CSVs and Combine to One Dataframe
file_one = "rollingsales_bronx.csv"
file_two = "rollingsales_brooklyn.csv"
file_three = "rollingsales_manhattan.csv"
file_four = "rollingsales_queens.csv"
file_five = "rollingsales_statenisland.csv"

bronx_pd = pd.read_csv(file_one)
brooklyn_pd = pd.read_csv(file_two)
manhattan_pd = pd.read_csv(file_three)
queens_pd = pd.read_csv(file_four)
staten_island_pd = pd.read_csv(file_five)
sales_df = pd.concat([manhattan_pd, bronx_pd, brooklyn_pd, queens_pd, staten_island_pd])

#Clean missing rows, change Borough numbers to names and sort out residential buildings
sales_df = sales_df.replace('-', np.nan).dropna()
sales_df['BOROUGH'] = sales_df['BOROUGH'].map({1:'Manhattan', 2:'Bronx', 3:'Brooklyn', 4:'Queens', 5:'Staten Island'})
sales_df['BUILDING CLASS'], sales_df['CATEGORY'] = sales_df['BUILDING CLASS CATEGORY'].str.split(' ', 1).str
del (sales_df['BUILDING CLASS CATEGORY'], sales_df['BLOCK'], sales_df['LOT'],  sales_df['EASE-MENT'],  sales_df['TAX CLASS AT PRESENT'],
     sales_df['TAX CLASS AT TIME OF SALE'])
sales_df = sales_df.replace('-', np.nan).dropna()
sales_df = sales_df[~sales_df['BUILDING CLASS'].isin(['11A'])]
sales_df[['BUILDING CLASS']] = sales_df[['BUILDING CLASS']].apply(pd.to_numeric)

sales_df

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,BUILDING CLASS,CATEGORY
0,Manhattan,INWOOD,A5,49 MARBLE HILL AVENUE,,10463,1.0,0,1,1219,1224,1920,A5,635000,8/18/17,1,ONE FAMILY DWELLINGS
1,Manhattan,WASHINGTON HEIGHTS LOWER,A9,16 SYLVAN TERRACE,,10032,1.0,0,1,673,1425,1899,A9,1560000,9/28/17,1,ONE FAMILY DWELLINGS
6,Manhattan,MURRAY HILL,A4,130 EAST 38TH STREET,,10016,1.0,0,1,491,1824,1910,A4,2650000,5/9/17,1,ONE FAMILY DWELLINGS
7,Manhattan,GREENWICH VILLAGE-WEST,S1,21 EIGHTH AVENUE,,10014,1.0,1,2,757,1854,1900,S1,5550000,7/12/17,1,ONE FAMILY DWELLINGS
8,Manhattan,GREENWICH VILLAGE-WEST,A9,58 DOWNING STREET,,10014,1.0,0,1,1067,1920,1899,A9,5430000,6/28/17,1,ONE FAMILY DWELLINGS
9,Manhattan,MURRAY HILL,A4,132 EAST 38TH STREET,,10016,1.0,0,1,495,1920,1910,A4,3850000,7/10/17,1,ONE FAMILY DWELLINGS
10,Manhattan,INWOOD,A1,55 ADRIAN AVENUE,,10463,1.0,0,1,2500,1938,1910,A1,637500,11/3/17,1,ONE FAMILY DWELLINGS
11,Manhattan,UPPER EAST SIDE (79-96),A9,123 EAST 92ND STREET,,10128,1.0,0,1,1258,1992,1910,A9,4150000,9/25/17,1,ONE FAMILY DWELLINGS
12,Manhattan,HARLEM-UPPER,A9,602 W 147TH STREET,,10031,1.0,0,1,1499,2307,1926,A9,1950000,5/19/17,1,ONE FAMILY DWELLINGS
13,Manhattan,GREENWICH VILLAGE-WEST,S1,66 GREENWICH AVENUE,,10011,1.0,1,2,925,2337,1910,S1,4065000,8/3/17,1,ONE FAMILY DWELLINGS
14,Manhattan,HARLEM-UPPER,A4,103 HAMILTON PLACE,,10031,1.0,0,1,1080,2394,1910,A4,2800000,7/20/17,1,ONE FAMILY DWELLINGS
15,Manhattan,GREENWICH VILLAGE-WEST,A4,75 BEDFORD STREET,,10014,1.0,0,1,1640,2400,1901,A4,7800000,8/15/17,1,ONE FAMILY DWELLINGS
16,Manhattan,UPPER EAST SIDE (79-96),A4,558 EAST 87TH STREET,,10128,1.0,0,1,692,2432,1899,A4,4495000,1/11/17,1,ONE FAMILY DWELLINGS
17,Manhattan,HARLEM-EAST,A5,122 EAST 101ST STREET,,10029,1.0,0,1,1716,2563,1890,A5,3900000,8/31/17,1,ONE FAMILY DWELLINGS
18,Manhattan,UPPER EAST SIDE (59-79),A4,259 EAST 78TH ST,,10075,1.0,0,1,1413,2600,1899,A4,4000000,7/24/17,1,ONE FAMILY DWELLINGS
19,Manhattan,UPPER EAST SIDE (59-79),A4,249 EAST 71ST STREET,,10021,1.0,0,1,1890,2700,1899,A4,6350000,8/7/17,1,ONE FAMILY DWELLINGS
23,Manhattan,HARLEM-CENTRAL,A4,11 EAST 129 STREET,,10035,1.0,0,1,1081,2800,1905,A4,925000,11/21/17,1,ONE FAMILY DWELLINGS
24,Manhattan,UPPER EAST SIDE (59-79),A4,340 EAST 69TH STREET,,10021,1.0,0,1,1289,2880,1899,A4,6220000,9/7/17,1,ONE FAMILY DWELLINGS
25,Manhattan,UPPER EAST SIDE (79-96),S1,160 EAST 93RD STREET,,10128,1.0,1,2,1661,2880,1901,S1,4400000,10/12/17,1,ONE FAMILY DWELLINGS
29,Manhattan,UPPER WEST SIDE (79-96),A9,47 WEST 94TH STREET,,10025,1.0,0,1,1435,3050,1900,A9,3500000,3/17/17,1,ONE FAMILY DWELLINGS
31,Manhattan,MIDTOWN EAST,A4,213 EAST 48TH STREET,,10017,1.0,0,1,1665,3060,1899,A4,5000000,2/15/17,1,ONE FAMILY DWELLINGS
34,Manhattan,GREENWICH VILLAGE-CENTRAL,A5,62 WEST 12TH STREET,,10011,1.0,0,1,1996,3200,1901,A5,9500000,7/7/17,1,ONE FAMILY DWELLINGS
35,Manhattan,HARLEM-CENTRAL,A9,307 WEST 136 STREET,,10030,1.0,0,1,1665,3200,1910,A9,1510000,1/3/17,1,ONE FAMILY DWELLINGS
36,Manhattan,HARLEM-EAST,S1,333 EAST 116 STREET,,10029,1.0,1,2,1682,3200,1899,S1,375000,10/10/17,1,ONE FAMILY DWELLINGS
38,Manhattan,GREENWICH VILLAGE-WEST,A4,57 BANK STREET,,10014,1.0,0,1,1296,3202,1899,A4,12550000,11/21/17,1,ONE FAMILY DWELLINGS
39,Manhattan,GREENWICH VILLAGE-WEST,S1,395 BLEECKER STREET,,10014,1.0,1,2,1425,3288,1899,S1,11139450,3/9/17,1,ONE FAMILY DWELLINGS
41,Manhattan,UPPER EAST SIDE (79-96),A4,159 EAST 82ND STREET,,10028,1.0,0,1,1572,3420,1899,A4,7000000,6/2/17,1,ONE FAMILY DWELLINGS
42,Manhattan,UPPER EAST SIDE (79-96),A4,161 EAST 82ND STREET,,10028,1.0,0,1,1572,3420,1899,A4,7000000,6/22/17,1,ONE FAMILY DWELLINGS
43,Manhattan,HARLEM-CENTRAL,A4,226 WEST 132 STREET,,10027,1.0,0,1,1665,3432,1910,A4,2720000,10/26/17,1,ONE FAMILY DWELLINGS
44,Manhattan,UPPER EAST SIDE (79-96),S1,1318 MADISON AVENUE,,10128,1.0,1,2,1404,3460,1910,S1,6210000,2/9/17,1,ONE FAMILY DWELLINGS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8552,Staten Island,WOODROW,B2,22 MARISA CIRCLE,,10309,2.0,0,2,6266,2465,1984,B2,665000,10/24/17,2,TWO FAMILY DWELLINGS
8553,Staten Island,WOODROW,B2,60 MARISA CIRCLE,,10309,2.0,0,2,2685,2265,1984,B2,570000,5/31/17,2,TWO FAMILY DWELLINGS
8555,Staten Island,WOODROW,B2,136 MARISA CIRCLE,,10309,2.0,0,2,3640,2576,1984,B2,722000,2/7/17,2,TWO FAMILY DWELLINGS
8556,Staten Island,WOODROW,B2,149 MARISA CIRCLE,,10309,2.0,0,2,2943,1976,1984,B2,545000,12/29/16,2,TWO FAMILY DWELLINGS
8557,Staten Island,WOODROW,B2,153 MARISA CIRCLE,,10309,2.0,0,2,2807,1960,1984,B2,471510,8/18/17,2,TWO FAMILY DWELLINGS
8558,Staten Island,WOODROW,B2,61 HELENE COURT,,10309,2.0,0,2,3784,2472,1984,B2,740000,10/24/17,2,TWO FAMILY DWELLINGS
8559,Staten Island,WOODROW,B2,574 MAGUIRE AVENUE,,10309,2.0,0,2,21528,2650,1985,B2,875000,5/22/17,2,TWO FAMILY DWELLINGS
8560,Staten Island,WOODROW,B2,72 DEXTER AVENUE,,10309,2.0,0,2,5260,2600,2001,B2,840000,12/7/16,2,TWO FAMILY DWELLINGS
8561,Staten Island,WOODROW,B2,56 DEXTER AVENUE,,10309,2.0,0,2,8306,2600,2001,B2,772500,3/30/17,2,TWO FAMILY DWELLINGS
8562,Staten Island,WOODROW,B2,35 LYNBROOK AVENUE,,10309,2.0,0,2,5060,2600,2001,B2,740000,1/4/17,2,TWO FAMILY DWELLINGS
8565,Staten Island,WOODROW,B9,96 CRABTREE AVENUE,,10309,2.0,0,2,2337,1464,2010,B9,590000,3/1/17,2,TWO FAMILY DWELLINGS
8566,Staten Island,WOODROW,B9,98 CRABTREE AVENUE,,10309,2.0,0,2,2429,1298,2010,B9,580000,4/26/17,2,TWO FAMILY DWELLINGS
8567,Staten Island,WOODROW,B9,10 TRINA LANE,,10309,2.0,0,2,3936,1470,2004,B9,550000,6/20/17,2,TWO FAMILY DWELLINGS
8568,Staten Island,WOODROW,B2,125 CLAY PIT ROAD,,10309,2.0,0,2,10935,2683,1998,B2,800000,1/9/17,2,TWO FAMILY DWELLINGS
8569,Staten Island,WOODROW,B9,200 WIRT AVENUE,,10309,2.0,0,2,3447,1200,1998,B9,625000,11/1/17,2,TWO FAMILY DWELLINGS
8570,Staten Island,WOODROW,B9,65 SHARROTTS LANE,,10309,2.0,0,2,4300,2170,1998,B9,642500,6/22/17,2,TWO FAMILY DWELLINGS
8571,Staten Island,WOODROW,B2,27 RED CEDAR LANE,,10309,2.0,0,2,3985,2700,1996,B2,600000,2/27/17,2,TWO FAMILY DWELLINGS
8572,Staten Island,WOODROW,B2,21 RED CEDAR LANE,,10309,2.0,0,2,4065,2700,1996,B2,640000,9/22/17,2,TWO FAMILY DWELLINGS
8573,Staten Island,WOODROW,B9,30 HEMLOCK LANE,,10309,2.0,0,2,3801,2704,1996,B9,610000,12/5/16,2,TWO FAMILY DWELLINGS
8574,Staten Island,WOODROW,B2,33 WHITE OAK LANE,,10309,2.0,0,2,7885,2704,1996,B2,645000,8/4/17,2,TWO FAMILY DWELLINGS
8575,Staten Island,WOODROW,B2,43 WHITE OAK LANE,,10309,2.0,0,2,2535,2700,1996,B2,625000,8/30/17,2,TWO FAMILY DWELLINGS
8576,Staten Island,WOODROW,B2,19 SPRUCE LANE,,10309,2.0,0,2,3800,2700,1996,B2,52400,9/19/17,2,TWO FAMILY DWELLINGS
8577,Staten Island,WOODROW,B2,19 SPRUCE LANE,,10309,2.0,0,2,3800,2700,1996,B2,168000,1/19/17,2,TWO FAMILY DWELLINGS
8581,Staten Island,WOODROW,B9,108 DARNELL LANE,,10309,2.0,0,2,2875,1500,1995,B9,610000,9/19/17,2,TWO FAMILY DWELLINGS
8582,Staten Island,WOODROW,B2,65 ROBIN COURT,,10309,2.0,0,2,5775,2160,1994,B2,685000,8/18/17,2,TWO FAMILY DWELLINGS
8583,Staten Island,WOODROW,B2,112 ROBIN COURT,,10309,2.0,0,2,11088,2160,1994,B2,648000,12/7/16,2,TWO FAMILY DWELLINGS
8585,Staten Island,WOODROW,B9,23 QUAIL LANE,,10309,2.0,0,2,4765,2575,1998,B9,690000,9/14/17,2,TWO FAMILY DWELLINGS
8586,Staten Island,WOODROW,B9,32 PHEASANT LANE,,10309,2.0,0,2,2498,2377,1998,B9,550000,4/21/17,2,TWO FAMILY DWELLINGS
8587,Staten Island,WOODROW,B2,49 PITNEY AVENUE,,10309,2.0,0,2,4000,1496,1925,B2,460000,7/5/17,2,TWO FAMILY DWELLINGS
8589,Staten Island,WOODROW,K6,2730 ARTHUR KILL ROAD,,10309,0.0,7,7,208033,64117,2001,K6,11693337,12/21/16,22,STORE BUILDINGS